# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing
__all__ = [
    "SqlSanitizerPluginCore",
]

@typing.final
class SqlSanitizerPluginCore:
    def __new__(cls, config: typing.Any) -> SqlSanitizerPluginCore: ...
    def prompt_pre_fetch(self, payload: typing.Any, context: typing.Any, extensions: typing.Any = None) -> typing.Any: ...
    def tool_pre_invoke(self, payload: typing.Any, context: typing.Any, extensions: typing.Any = None) -> typing.Any: ...
